# ABOUTME: Synthesises the royalty-free music bed (soft ambient pad + pulse) and the hospital monitor
# ABOUTME: SFX with numpy, so every sound in the video is generated by us and has no licensing risk.
import wave
from pathlib import Path

import numpy as np

SR = 48000


def _write(path: str, x: np.ndarray) -> None:
  x = np.clip(x, -1, 1)
  stereo = np.stack([x, x], axis=1) if x.ndim == 1 else x
  with wave.open(path, "wb") as w:
    w.setnchannels(2)
    w.setsampwidth(2)
    w.setframerate(SR)
    w.writeframes((stereo * 32767).astype(np.int16).tobytes())


def _lowpass(x: np.ndarray, cutoff: float) -> np.ndarray:
  a = np.exp(-2 * np.pi * cutoff / SR)
  y = np.empty_like(x)
  acc = 0.0
  for i, v in enumerate(x):
    acc = (1 - a) * v + a * acc
    y[i] = acc
  return y


def _note(freq: float, dur: float) -> np.ndarray:
  t = np.arange(int(dur * SR)) / SR
  # three slightly detuned voices + a soft octave: a warm pad
  tone = sum(np.sin(2 * np.pi * freq * d * t) for d in (0.997, 1.0, 1.003)) / 3
  tone += 0.25 * np.sin(2 * np.pi * freq * 2 * t)
  env = np.minimum(1, t / 1.2) * np.minimum(1, (dur - t) / 1.5)
  return tone * env


def music(total: float) -> np.ndarray:
  # Am - F - C - G, 4 s per chord, pad + a gentle plucked pulse on eighth notes (120 bpm)
  chords = [(220.0, 261.63, 329.63), (174.61, 220.0, 261.63), (130.81, 196.0, 261.63), (196.0, 246.94, 293.66)]
  bass = [110.0, 87.31, 65.41, 98.0]
  out = np.zeros(int(total * SR) + SR)
  step, i, t0 = 4.0, 0, 0.0
  while t0 < total:
    k = i % 4
    seg = sum(_note(f, step + 1.5) for f in chords[k]) / 3 * 0.5 + _note(bass[k], step + 1.5) * 0.35
    s = int(t0 * SR)
    out[s:s + len(seg)] += seg[:len(out) - s]
    for j in range(8):
      p0 = int((t0 + j * 0.5) * SR)
      tt = np.arange(int(0.35 * SR)) / SR
      f = chords[k][j % 3] * 2
      pluck = np.sin(2 * np.pi * f * tt) * np.exp(-tt * 9) * 0.12
      out[p0:p0 + len(pluck)] += pluck[:max(0, len(out) - p0)]
    t0 += step
    i += 1
  out = _lowpass(out[:int(total * SR)], 2500)
  return out / np.max(np.abs(out)) * 0.8


def monitor_sfx() -> np.ndarray:
  # two heartbeat blips (27.0, 27.8 in video time) then a flatline tone from 28.6, fading by 30.4
  length = 3.6
  out = np.zeros(int(length * SR))
  def beep(start: float, dur: float, fade: float = 0.01) -> None:
    t = np.arange(int(dur * SR)) / SR
    env = np.minimum(1, t / 0.005) * np.minimum(1, (dur - t) / fade)
    s = int(start * SR)
    out[s:s + len(t)] += np.sin(2 * np.pi * 1000 * t) * env * 0.5
  beep(0.0, 0.12)
  beep(0.8, 0.12)
  beep(1.6, 1.95, fade=0.6)
  return out


Path("audio").mkdir(exist_ok=True)
_write("audio/music_bed.wav", music(118.0))   # plays 59.0 -> 177.0
_write("audio/sfx_monitor.wav", monitor_sfx())  # plays at 27.0
print("ok")
